USE ITCREW;

SET collation_connection = @@collation_database;
DROP TABLE IF EXISTS `tb_menu_set`;
CREATE TABLE `tb_menu_set` (
	`SEQ_NO` BIGINT NOT NULL AUTO_INCREMENT,
	`TYPE` VARCHAR(50) NOT NULL,
	`DEPTH1` VARCHAR(50) NULL,
	`DEPTH2` VARCHAR(50) NULL,
	`Parent_Id` BIGINT NOT NULL DEFAULT 0,
	`URL` VARCHAR(50) NULL,
	`CHG_USR_NO` BIGINT NULL,
	`CHG_DATE` DATETIME NULL,
	`ACTIVE_FLAG` VARCHAR(50) NULL DEFAULT 'T',
	PRIMARY KEY (`SEQ_NO`),
	Index(`TYPE`)
)
COLLATE='utf8mb4_general_ci'