USE ITCREW;

SET collation_connection = @@collation_database;
DROP TABLE IF EXISTS `tb_subj_reply`;
CREATE TABLE `tb_subj_reply` (
	`SUBJ_ID` BIGINT NOT NULL,
	`REPLY_ID` BIGINT NOT NULL AUTO_INCREMENT,
	`User_No` BIGINT NOT NULL,
	`DESC` VARCHAR(50) NULL DEFAULT '',
	`PARENT_ID` BIGINT NULL,
	`LAST_CHG_USR` BIGINT,
	`CHG_DATE` DATETIME NULL,
	`ACTIVE_FLAG` VARCHAR(50) NULL DEFAULT 'T',
	PRIMARY KEY (`REPLY_ID`),
	INDEX `TB_SUBJ_REPLY_FK` (`SUBJ_ID`),
	FOREIGN KEY (`User_No`) REFERENCES `itcrew`.`tb_user_info` (`USER_NO`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8mb4_general_ci'
