USE ITCREW;
SET collation_connection = @@collation_database;
DROP TABLE IF EXISTS tb_subj_info;
CREATE TABLE `tb_subj_info` (
	`SUBJ_ID` BIGINT NOT NULL AUTO_INCREMENT,
	`TYPE` VARCHAR(50) NOT NULL,
	`TITLE` VARCHAR(50) NOT NULL,
	`DESC` VARCHAR(5000) NULL,
	`CHG_USER_NO` BIGINT NOT NULL,
	`CHG_DATE` DATETIME NULL,
	`ACTIVE_FLAG` VARCHAR(50) NULL ,
	PRIMARY KEY (`SUBJ_ID`)
)
COLLATE='utf8mb4_general_ci';


